language: node_js
node_js:
  - "16.20.1"

cache:
  directories:
    - node_modules

addons:
  sonarcloud:
    organization: "vlavrynovych"

install:
  - npm install

script:
  - npm run coverage
  - npm run coverage:coveralls

  - echo "sonar.projectKey=vlavrynovych:msr" > sonar-project.properties
  - echo "sonar.projectVersion=develop" >> sonar-project.properties
  - echo "sonar.projectName=Migration Script Runner" >> sonar-project.properties

  - sonar-scanner