language: node_js
node_js:
  - "16.20.1"

cache:
  directories:
    - node_modules

addons:
  sonarcloud:
    organization: "vlavrynovych"

install:
  - npm install

script:
  - npm run coverage

  - echo "service_name:: travis-ci" > .coveralls.yml
  - echo "service_job_id:: $TRAVIS_BUILD_ID" >> .coveralls.yml
  - echo "service_build_url:: $TRAVIS_BUILD_WEB_URL" >> .coveralls.yml
  - echo "service_branch:: $TRAVIS_PULL_REQUEST_BRANCH" >> .coveralls.yml
  - echo "service_pull_request:: $TRAVIS_PULL_REQUEST" >> .coveralls.yml
  - echo "repo_token:: 2XqaHJJuzJIBjZ0l5b1yOOAlE9B3kY6EB" >> .coveralls.yml

  - npm run coverage:coveralls
  - npm run lint:report

  - echo "sonar.projectKey=vlavrynovych_msr" > sonar-project.properties
  - echo "sonar.organization=vlavrynovych" >> sonar-project.properties
  - echo "sonar.projectVersion=develop" >> sonar-project.properties
  - echo "sonar.projectName=MSR" >> sonar-project.properties
  - echo "sonar.javascript.lcov.reportPaths=./reports/coverage/lcov.info" >> sonar-project.properties

  - sonar-scanner