source "https://rubygems.org"

gem "jekyll", "~> 3.9.0"
gem "just-the-docs", "0.4.0"
gem "webrick"
gem "kramdown-parser-gfm"

group :jekyll_plugins do
  gem "jekyll-seo-tag"
  gem "jekyll-remote-theme"
  gem "jekyll-include-cache"
end
